---
env: wp
hostname: wp.example.com
sshd: 
  - { port: 22, rootlogin: 'yes', passwordauth: 'yes' }
users:
  - { name: 'root', pass: 'password', homedir: '/root', sudo: false, sshkeypass: "", publickey: "" }
  - { name: 'wpadmin', pass: 'password', homedir: '/var/www/vhosts', sudo: true, sshkeypass: "sshkeypass", publickey: "" }
mysqld_server_root_passwd: password
mysqld_server_innodb_flush_log_at_trx_commit: 2
php_execution_user: wpadmin
php_fpm_execution_user: wpadmin
php_fpm_listen: /var/run/php-fpm.sock
nginx_user: wpadmin
phpmyadmin_config_readable_group: wpadmin
wordpress_install_path: /var/www/vhosts
zabbix_agent_servers: 127.0.0.1
