---
- name: Set wp-setup command
  template: src='wp-setup.j2' dest='/usr/local/sbin/wp-setup' owner=root group=root mode=0750

- name: Set install-wp.sh command
  template: src='install-wp.sh.j2' dest='/usr/local/sbin/install-wp.sh' owner=root group=root mode=0750

- name: Set create_config.sh command
  template: src='create_config.sh.j2' dest='/usr/local/sbin/create_config.sh' owner=root group=root mode=0750

- name: Set create_default_config.sh command
  template: src='create_default_config.sh.j2' dest='/usr/local/sbin/create_default_config.sh' owner=root group=root mode=0750

- file: path={{ wordpress_install_path }} state=directory mode=0751

- name: Check wordpres files
  shell: ls {{ wordpress_install_path }} 2>/dev/null | wc -l 2>/dev/null
  register: file_count
  changed_when: false
  always_run: yes

- name: Install Wordpress
  command: /usr/local/sbin/wp-setup default default
  when: file_count.stdout == '0'
  #shell: /usr/local/sbin/wp-setup default default
